### PR TITLE
V3

### PR DESCRIPTION
**Pull request by vadimdemedes**

### CODE REVIEW

**Comment by zaaack** [comment]
IMHO, using redux to control model state is a great and but also a little radical, creating a store for each document wouldn't cause too much performance loss?

**Comment by zaaack** [comment]
What about just create one single store for each collection, and using _id or just model reference to dispatch action?

**Comment by vadimdemedes** [comment]
Not really, Redux is simple and lightweight, it doesn't do anything heavy under the hood. I tried to implement the flexible and predictable plugin system, but I wasn't satisfied with either of my ideas. Redux's middleware concept provides everything I've been looking for and gives the community a great power over how Mongorito works.

**Comment by vadimdemedes** [comment]
Developers will be able to write plugins with access to pretty much every operation happening in a model. I believe this flexibility is worth a tiny perf loss. In reality, JS perf isn't the problem, I/O is.

**Comment by zaaack** [comment]
@vadimdemedes I see, but createStore would create many functions in closure, it's designed to call once(so these functions only create once), would this cause GC too frequently? (I haven't tried actually, just a worry)

**Comment by vadimdemedes** [comment]
Why would you assume `createStore` is designed to call once? How about server rendering? See http://redux.js.org/docs/recipes/ServerRendering.html#handling-the-request.

**Comment by zaaack** [comment]
@vadimdemedes Ok, Maybe I have a little overthinking. Thanks for your explanation.

**Comment by vadimdemedes** [comment]
@zaaack No probs, thank you for your constant involvement with Mongorito!

**Comment by zaaack** [comment]
Mongorito is awesome, and I can't find these features in any other ODM,  I'm really excited about v4, thanks for your great work!

**Comment by brielov** [comment]
I had to switch recently to mongoose just because I needed elasticsearch integration and the only solution I could find was mongoosastic. Its killing me because I really love mongorito and its beautiful syntax. The minute you implement a plugin system, I'll switch back to mongorito. <3

**Comment by paulxuca** [comment]
🎆 🎉

**Pull request merged**
