### PR TITLE
allow .then on Query

### PR DESCRIPTION
**Pull request by EduardoRFS**
When execute mquery methods on Query class, not have .then method

before:

``` javascript
Post.where('_id', 1).then() // error non function
Post.findOneAndUpdate(...).then() // error non function
```

after:

``` javascript
Post.where('_id', 1).then() // Promise
Post.findOneAndUpdate(...).then() // Promise

await Post.findOneAndUpdate(...) // works
```

### CODE REVIEW

**Comment by vdemedes** [comment]
Good suggestion, but to make `.catch()` work, I'd implement that like:

```js
then() {
  return new Promise((resolve, reject) => {
    return new this.model.dbCollection()
      .then(collection => this.mquery.collection(collection))
      .then(resolve, reject);
  });
}
```

Also, do you mind adding a test to confirm it's working?

**Comment by EduardoRFS** [comment]
@vdemedes refactored Query, removed unnecessary code and allowed syntax like `.findOne().where(...)`, `.catch` is after `.then` ex: `.findOne().then(...).catch(...)`. Basically with this PR Query is a `instanceof` mquery, with custom `.then` all tests use `.then`

**Comment by vdemedes** [comment]
Could you revert this PR back to its original point, without making `Query` extend `mquery`?

In future, please consider opening an issue or discussing in the PR first, before making major changes. That way, you avoid extra work that might be rejected and you don't waste your precious time ;)

**Comment by EduardoRFS** [comment]
Reverted, i make that to use in a project. Is only a suggestion

**Comment by zaaack** [comment]
Recently I hit this issue too,  at first I expose mquery  instance and implement  then method to using findOneAndUpdate, then I realize  the return is just like the native driver, to using like mongorito still need write hooks and wrap, like an wrap method of query, other hand the dbCollection is enough.

**Comment by vadimdemedes** [comment]
Closing, turns out this is a bad practice, see https://github.com/vadimdemedes/mongorito/issues/176.

**Pull request closed without merging**
